server:
    port: 9090
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://101.43.98.156:3306/hub
        username: root
        password: yjhui
    quartz:
        # quartz任务存储类型：jdbc或memory
        job-store-type: jdbc
        # 关闭时等待任务完成
        wait-for-jobs-to-complete-on-shutdown: true
        # 可以覆盖已有的任务
        overwrite-existing-jobs: true
        properties:
            org:
                quartz:
                    scheduler:
                        # 调度器实例名称
                        instanceName: scheduler
                        # 调度器实例ID自动生成
                        instanceId: AUTO
                    jobStore:
                        class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
                        driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
                        # quartz相关表前缀
                        tablePrefix: QRTZ_
                        useProperties: false
                    threadPool:
                        class: org.quartz.simpl.SimpleThreadPool
                        # 设置并发线程数量
                        threadCount: 10
                        # 指定线程优先级
                        threadPriority: 5
                        threadsInheritContextClassLoaderOfInitializingThread: true
redisson:
    address: redis://101.43.98.156:6379
    password: 123456